# Workflow básico

name: CI

# Controla quando a ação será executada.
on:
 # Aciona o fluxo de trabalho em eventos de solicitação push ou pull, mas apenas para o branch principal
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
  # Permite que você execute este fluxo de trabalho manualmente na guia Ações
  workflow_dispatch:

# A execução de um fluxo de trabalho é composta por uma ou mais tarefas que podem ser executadas sequencialmente ou em paralelo
jobs:
 # Este fluxo de trabalho contém um único trabalho denominado "build"
  build:
   # O tipo de sistema operacional que vai executar a job
    runs-on: ubuntu-latest

    # As etapas representam uma sequência de tarefas que serão executadas como parte do trabalho
    steps:
     # Faz o check-out de seu repositório em $ GITHUB_WORKSPACE, para que seu trabalho possa acessá-lo
      - uses: actions/checkout@v2

        # Executa um único comando usando o shell do runners
      - name: Run a one-line script
        run: echo Hello, world!

        # Executa um conjunto de comandos usando o shell do runners
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
